const checkboxOptions = [
  { name: "Party Name", value: "partyName", defaultCheck: true },
  { name: "Type of Loan", value: "typeOfLoan", defaultCheck: true },
  {
    name: "Display Name",
    value: "displayName",
    defaultCheck: false,
  },
  {
    name: "User ID / Password",
    value: "userIdPassword",
    defaultCheck: false,
  },
  { name: "Email Address", value: "emailAddress", defaultCheck: false },
  { name: "Upload Image", value: "uploadImage", defaultCheck: false },
  { name: "Address", value: "address", defaultCheck: false },
  { name: "Incentive", value: "incentive", defaultCheck: false },
  { name: "GST Number", value: "gstNumber", defaultCheck: false },
  { name: "Range", value: "range", defaultCheck: false },
  { name: "State", value: "state", defaultCheck: false },
  {
    name: "Method of Payment",
    value: "methodOfPayment",
    defaultCheck: false,
  },
  { name: "City", value: "city", defaultCheck: false },
  { name: "Target (Type of Loan)", value: "target", defaultCheck: false },
  { name: "Pin Code", value: "pinCode", defaultCheck: false },
  { name: "Minimum file size", value: "minFile", defaultCheck: false },
  { name: "Mobile Number", value: "mobileNumber", defaultCheck: false },
  { name: "Salary", value: "salary", defaultCheck: false },
  { name: "Update URL", value: "updateUrl", defaultCheck: false },
  { name: "Level", value: "level", defaultCheck: false },
  {
    name: "Account holder name",
    value: "accountHolderName",
    defaultCheck: false,
  },
  { name: "Upgrade New Plan", value: "upgradeNewPlan", defaultCheck: false },
  { name: "Bank Name", value: "bankName", defaultCheck: false },
  { name: "Account No.", value: "accountNo", defaultCheck: false },
  { name: "IFSC Code", value: "ifscCode", defaultCheck: false },
  { name: "Upload Pan Card", value: "uploadPanCard", defaultCheck: false },
  { name: "Minimum Business", value: "minimumBusiness", defaultCheck: false },
  {
    name: "Upload Aadhaar Card",
    value: "uploadAadhaarCard",
    defaultCheck: false,
  },
  { name: "Minimum Payout", value: "minimumPayout", defaultCheck: false },
  { name: "Benefits", value: "benefits", defaultCheck: false },
  {
    name: "Compulsory Requirement",
    value: "compulsoryRequirement",
    defaultCheck: false,
  },
  { name: "Job description", value: "jobDescription", defaultCheck: false },
  {
    name: "No. of Job Vacancy",
    value: "noOfJobVacancy",
    defaultCheck: false,
  },
  { name: "Job deadlines", value: "jobDeadlines", defaultCheck: false },
  { name: "Is this primary?", value: "isPrimary", defaultCheck: false },
  {
    name: "Is this primary or sub-primary?",
    value: "isPrimaryOrSubPrimary",
    defaultCheck: false,
  },
  { name: "Level Number", value: "levelNumber", defaultCheck: false },
  { name: "Level Name", value: "levelName", defaultCheck: false },
];

export default checkboxOptions;
